### ISSUE TITLE
Problem with files opening

### ISSUE THREAD

**Issue by GuillaumeHolley** [Malfoy/Blight#6]
Hi there,

I am trying to query a graph built with BCALM2 using Blight. The command looks as follow:
```
./Blight/bench_blight -g bcalm_graph.unitigs.fa -q queries.fa -k 31 -t 4
```
And the output is:
```
I use -k 31 -m  10 -n  0 -s  4 -t 4 -b 0
Build index from file bcalm_graph.unitigs.fa
Problem with files opening
```

Any idea what is happening here?

I had also a question regarding the querying itself: Does Blight queries all k-mers of each query or only a subset of them? Is there a threshold available for this as a parameter of Blight?

Thank you for the help ;)

Guillaume

**Comment by Malfoy** [comment]
Hi!

Sorry for this problem, this snippet now writes temporary files in a working directory "wdir". 
It should be fixed with the last commit if you run bench_blight in its repository, if not please create an empty directory "wdir".

**Comment by GuillaumeHolley** [comment]
Thanks for having a look. Unfortunately, compilation fails with the latest commit:
```
g++ -o bench_minitig.o -c bench_minitig.cpp -DNDEBUG -Ofast -flto -march=native -mtune=native -g -std=c++11 -pipe -lz -fopenmp -msse4 
g++ -o minitig.o -c minitig.cpp -DNDEBUG -Ofast -flto -march=native -mtune=native -g -std=c++11 -pipe -lz -fopenmp -msse4 
g++ -o blight.o -c blight.cpp -DNDEBUG -Ofast -flto -march=native -mtune=native -g -std=c++11 -pipe -lz -fopenmp -msse4 
g++ -o utils.o -c utils.cpp -DNDEBUG -Ofast -flto -march=native -mtune=native -g -std=c++11 -pipe -lz -fopenmp -msse4 
gcc -o trlec.o -c trlec.c -w -Wall -std=gnu99 -DUSE_THREADS  -fstrict-aliasing -Iext 
trlec.c:28:10: fatal error: conf.h: No such file or directory
 #include "conf.h"
          ^~~~~~~~
compilation terminated.
makefile:50: recipe for target 'trlec.o' failed
make: *** [trlec.o] Error 1
```

**Comment by Malfoy** [comment]
Oops I forgot a file.
It should be ok now!

**Comment by GuillaumeHolley** [comment]
Thanks, it compiles and runs now :)

I am a little bit confused on the output of Blight though. I don't see an output file and the "QUERY PRESENCE RECAP" output of Blight gives me a number of "Good kmer" and "Erroneous kmers". So I was wondering what is a good k-mer and an erroneous k-mer? In general, how do I know which of my queries are present and which are not?

Thanks for the help!

Guillaume

**Comment by Malfoy** [comment]
A good kmer is a kmer found in the index and an erroneous kmer is a kmer absent from the index.
I will change this confusing message soon.

**Comment by GuillaumeHolley** [comment]
Oh I see, thanks for the clarification!
